const POWER_MODIFIERS_LIST = [
  // Extras
  { name: "Action (Extra)", cost: 1, costType: "per_rank", category: "extra", hasRanks: true, maxRanks: 3, tiers: ["Rank 1: Standard to Move", "Rank 2: Move to Free", "Rank 3: Free to Reaction"], fullText: "<p>Decreases the action required to use a power.</p>" },
  { name: "Affects Corporeal", cost: 1, costType: "flat", category: "extra", fullText: "<p>An incorporeal character can use this power on the physical world.</p>" },
  { name: "Affects Insubstantial", cost: 1, costType: "flat", category: "extra", hasRanks: true, maxRanks: 2, tiers: ["Rank 1: Half effect", "Rank 2: Full effect"], fullText: "<p>This power can affect insubstantial targets.</p>" },
  { name: "Affects Objects", cost: 1, costType: "per_rank", category: "extra", fullText: "<p>Powers that normally only affect living creatures can affect objects.</p>" },
  { name: "Affects Others", cost: 1, costType: "per_rank", category: "extra", fullText: "<p>You can grant a personal power to someone else by touching them.</p>" },
  { name: "Alternate Save", cost: 1, costType: "per_rank", category: "extra", fullText: "<p>The power requires a different saving throw than usual.</p>" },
  { name: "Area", cost: 1, costType: "per_rank", category: "extra", fullText: "<p>The power affects an area rather than a single target.</p>" },
  { name: "Aura", cost: 1, costType: "per_rank", category: "extra", fullText: "<p>The power surrounds your body. Anyone touching you or striking you in melee suffers the effect.</p>" },
  { name: "Autofire", cost: 1, costType: "per_rank", category: "extra", hasRanks: true, maxRanks: 3, tiers: ["Rank 1: Max +5 bonus", "Rank 2: Max +10 bonus", "Rank 3: Unlimited bonus"], fullText: "<p>You can hit the target multiple times, increasing the damage if you aim well.</p>" },
  { name: "Contagious", cost: 1, costType: "per_rank", category: "extra", fullText: "<p>The power spreads to others who touch the target.</p>" },
  { name: "Disease", cost: 2, costType: "per_rank", category: "extra", fullText: "<p>The power's effect is treated as a disease.</p>" },
  { name: "Duration (Extra)", cost: 1, costType: "per_rank", category: "extra", hasRanks: true, maxRanks: 2, tiers: ["Rank 1: Instant to Sustained (or similar step)", "Rank 2: Sustained to Continuous"], fullText: "<p>Increases the duration of a power.</p>" },
  { name: "Independent", cost: 0, costType: "per_rank", category: "extra", fullText: "<p>The power maintains itself once activated but fades.</p>" },
  { name: "Linked", cost: 0, costType: "flat", category: "extra", fullText: "<p>Two or more powers are linked and always operate together as a single action.</p>" },
  { name: "No Saving Throw", cost: 2, costType: "per_rank", category: "extra", fullText: "<p>The power does not allow a saving throw.</p>" },
  { name: "Penetrating", cost: 1, costType: "flat", category: "extra", hasRanks: true, maxRanks: 20, fullText: "<p>The power ignores Impervious Toughness.</p>" },
  { name: "Poison", cost: 1, costType: "per_rank", category: "extra", fullText: "<p>The power requires a secondary save 1 minute later.</p>" },
  { name: "Range (Extra)", cost: 1, costType: "per_rank", category: "extra", hasRanks: true, maxRanks: 2, tiers: ["Rank 1: Touch to Ranged", "Rank 2: Ranged to Perception"], fullText: "<p>Increases the range of a power.</p>" },
  { name: "Selective Attack", cost: 1, costType: "per_rank", category: "extra", fullText: "<p>You can choose who in an Area is affected by your power.</p>" },
  { name: "Sleep", cost: 0, costType: "flat", category: "extra", fullText: "<p>An effect that normally causes unconsciousness causes the target to fall asleep.</p>" },
  { name: "Targeted", cost: 0, costType: "per_rank", category: "extra", fullText: "<p>An Area effect requires an attack roll against a specific target to originate the area on them.</p>" },
  { name: "Total Fade", cost: 1, costType: "per_rank", category: "extra", fullText: "<p>Used with the Fades flaw or Independent extra.</p>" },
  { name: "Vampiric", cost: 1, costType: "per_rank", category: "extra", fullText: "<p>When you damage a target with this power, you heal a damage condition yourself.</p>" },
  
  // Progression (Available as Extras and Power Feats)
  { name: "Progression", cost: 1, costType: "flat", category: "extra", hasRanks: true, maxRanks: 20, fullText: "<p>Moves one step up the progression table for the power's effect (mass, area, range, targets, duration, etc.).</p>" },
  { name: "Progression (Area)", cost: 1, costType: "flat", category: "extra", hasRanks: true, maxRanks: 20, fullText: "<p>Each rank moves the area of your power one step up the Time and Value Progression Table.</p>" },
  { name: "Progression (Duration)", cost: 1, costType: "flat", category: "extra", hasRanks: true, maxRanks: 20, fullText: "<p>Each rank moves the duration of your power one step up the Time and Value Progression Table.</p>" },
  { name: "Progression (Mass)", cost: 1, costType: "flat", category: "extra", hasRanks: true, maxRanks: 20, fullText: "<p>Each rank moves the mass or weight you can affect or carry one step up the Time and Value Progression Table.</p>" },
  { name: "Progression (Range)", cost: 1, costType: "flat", category: "extra", hasRanks: true, maxRanks: 20, fullText: "<p>Each rank moves the range of your power one step up the Time and Value Progression Table.</p>" },
  { name: "Progression (Targets)", cost: 1, costType: "flat", category: "extra", hasRanks: true, maxRanks: 20, fullText: "<p>Each rank increases the number of subjects or targets you can affect along the progression table.</p>" },
  
  // Flaws
  { name: "Action (Flaw)", cost: -1, costType: "per_rank", category: "flaw", hasRanks: true, maxRanks: 3, tiers: ["Rank 1: Standard to Full-Round", "Rank 2: Move to Standard", "Rank 3: Free to Move"], fullText: "<p>Increases the action required to use a power.</p>" },
  { name: "Check Required", cost: -1, costType: "flat", category: "flaw", hasRanks: true, maxRanks: 10, fullText: "<p>You must make a skill or ability check to use the power successfully.</p>" },
  { name: "Concentration", cost: -1, costType: "per_rank", category: "flaw", fullText: "<p>Decreases duration to Concentration.</p>" },
  { name: "Distracting", cost: -1, costType: "per_rank", category: "flaw", fullText: "<p>You lose your dodge bonus to Defense when using this power.</p>" },
  { name: "Duration (Flaw)", cost: -1, costType: "per_rank", category: "flaw", hasRanks: true, maxRanks: 3, tiers: ["Rank 1: Continuous to Sustained", "Rank 2: Sustained to Concentration", "Rank 3: Concentration to Instant"], fullText: "<p>Decreases the duration of a power.</p>" },
  { name: "Fades", cost: -1, costType: "per_rank", category: "flaw", fullText: "<p>The power loses effectiveness each time you use it.</p>" },
  { name: "Feedback", cost: -1, costType: "per_rank", category: "flaw", fullText: "<p>You suffer damage when your power's manifestation is attacked.</p>" },
  { name: "Full Power", cost: -1, costType: "flat", category: "flaw", fullText: "<p>You cannot voluntarily use the power at less than its maximum rank.</p>" },
  { name: "Grab-Based", cost: -1, costType: "per_rank", category: "flaw", fullText: "<p>You must successfully grapple a target before you can use this power on them.</p>" },
  { name: "Inaccurate", cost: -1, costType: "flat", category: "flaw", hasRanks: true, maxRanks: 10, fullText: "<p>The power is wildly inaccurate.</p>" },
  { name: "Limited", cost: -1, costType: "per_rank", category: "flaw", fullText: "<p>The power only works under specific conditions, against specific targets, or has half its normal utility.</p>" },
  { name: "Noticeable", cost: -1, costType: "flat", category: "flaw", fullText: "<p>A continuous or sustained power that is normally subtle is instead highly noticeable.</p>" },
  { name: "Range (Flaw)", cost: -1, costType: "per_rank", category: "flaw", hasRanks: true, maxRanks: 2, tiers: ["Rank 1: Perception to Ranged", "Rank 2: Ranged to Touch"], fullText: "<p>Decreases the range of a power.</p>" },
  { name: "Require Material", cost: -1, costType: "flat", category: "flaw", fullText: "<p>You require a specific material component to use this power.</p>" },
  { name: "Resistible", cost: -1, costType: "per_rank", category: "flaw", fullText: "<p>A power that normally doesn't allow a saving throw now allows one.</p>" },
  { name: "Side-Effect", cost: -1, costType: "per_rank", category: "flaw", hasRanks: true, maxRanks: 2, tiers: ["Rank 1: Happens on failure", "Rank 2: Happens always"], fullText: "<p>Using the power triggers a detrimental effect on you.</p>" },
  { name: "Tiring", cost: -1, costType: "per_rank", category: "flaw", fullText: "<p>You suffer a level of fatigue every time you use this power.</p>" },
  { name: "Unreliable", cost: -1, costType: "per_rank", category: "flaw", fullText: "<p>The power only works part of the time.</p>" },
  
  { name: "Reaction", cost: 3, costType: "per_rank", category: "extra", fullText: "<p>The power functions automatically as a reaction in response to a specified trigger.</p>" },
  { name: "Secondary Effect", cost: 1, costType: "per_rank", category: "extra", fullText: "<p>The target suffers the full effect of the power again on the round following the initial attack.</p>" },
  { name: "Sustained", cost: 1, costType: "per_rank", category: "extra", fullText: "<p>Increases a concentration power's duration to sustained.</p>" },
  { name: "Continuous", cost: 1, costType: "per_rank", category: "extra", fullText: "<p>Increases a sustained power's duration to continuous; it remains in effect even when you are stunned or unconscious.</p>" },
  { name: "Touch", cost: -1, costType: "per_rank", category: "flaw", fullText: "<p>Reduces a ranged power's range to touch/close.</p>" },
  { name: "Personal", cost: -1, costType: "per_rank", category: "flaw", fullText: "<p>Reduces a touch power's range to personal only.</p>" },
  { name: "Permanent", cost: -1, costType: "per_rank", category: "flaw", fullText: "<p>A continuous power is permanently active and cannot be deactivated, nor can you use Extra Effort with it.</p>" },
  { name: "Sense-Dependent", cost: -1, costType: "per_rank", category: "flaw", fullText: "<p>The target must be able to perceive the effect with a specific sense to be affected.</p>" },
  
  // Power Feats
  { name: "Accurate", cost: 1, costType: "flat", category: "feat", hasRanks: true, maxRanks: 10, fullText: "<p>You gain a +2 bonus on attack rolls with the power per rank.</p>" },
  { name: "Affects Insubstantial", cost: 1, costType: "flat", category: "feat", hasRanks: true, maxRanks: 2, tiers: ["Rank 1: Half effect", "Rank 2: Full effect"], fullText: "<p>This power can affect insubstantial targets.</p>" },
  { name: "Dimensional", cost: 1, costType: "flat", category: "feat", hasRanks: true, maxRanks: 3, fullText: "<p>You can affect targets in other dimensions.</p>" },
  { name: "Extended Reach", cost: 1, costType: "flat", category: "feat", hasRanks: true, maxRanks: 10, fullText: "<p>Extends your reach with a close range power by 5 feet per rank.</p>" },
  { name: "Homing", cost: 1, costType: "flat", category: "feat", hasRanks: true, maxRanks: 10, fullText: "<p>An attack that misses gains another attack roll next round.</p>" },
  { name: "Improved Critical", cost: 1, costType: "flat", category: "feat", hasRanks: true, maxRanks: 10, fullText: "<p>Increases the critical threat range of your power.</p>" },
  { name: "Improved Range", cost: 1, costType: "flat", category: "feat", hasRanks: true, maxRanks: 3, fullText: "<p>Increases the range increment of your ranged power.</p>" },
  { name: "Incurable", cost: 1, costType: "flat", category: "feat", fullText: "<p>Damage caused by this power cannot be healed normally.</p>" },
  { name: "Indirect", cost: 1, costType: "flat", category: "feat", hasRanks: true, maxRanks: 3, fullText: "<p>The power can originate from a point other than you.</p>" },
  { name: "Innate", cost: 1, costType: "flat", category: "feat", fullText: "<p>The power is an inborn, natural part of your physiology or being. It cannot be nullified or countered.</p>" },
  { name: "Mighty", cost: 1, costType: "flat", category: "feat", fullText: "<p>You add your Strength bonus to the power's damage.</p>" },
  { name: "Precise", cost: 1, costType: "flat", category: "feat", fullText: "<p>You can use the power with exacting precision.</p>" },
  { name: "Reversible", cost: 1, costType: "flat", category: "feat", fullText: "<p>You can remove the effects of your power at will.</p>" },
  { name: "Ricochet", cost: 1, costType: "flat", category: "feat", hasRanks: true, maxRanks: 10, fullText: "<p>You can bounce an attack off solid surfaces to hit a target.</p>" },
  { name: "Sedation", cost: 1, costType: "flat", category: "feat", fullText: "<p>Keeps a target you rendered unconscious asleep.</p>" },
  { name: "Slow Fade", cost: 1, costType: "flat", category: "feat", hasRanks: true, maxRanks: 10, fullText: "<p>For fading powers, each rank moves the fade rate one step down the Time and Value Progression Table.</p>" },
  { name: "Split Attack", cost: 1, costType: "flat", category: "feat", hasRanks: true, maxRanks: 5, fullText: "<p>You can split your power's rank among multiple targets.</p>" },
  { name: "Subtle", cost: 1, costType: "flat", category: "feat", hasRanks: true, maxRanks: 2, tiers: ["Rank 1: Notice DC 20 to detect", "Rank 2: Completely undetectable"], fullText: "<p>The power is difficult or impossible to detect.</p>" },
  { name: "Terminal Velocity", cost: 1, costType: "flat", category: "feat", fullText: "<p>You can reorient yourself safely to eliminate falling velocity when using movement/teleportation effects.</p>" },
  { name: "Tether", cost: 1, costType: "flat", category: "feat", fullText: "<p>Creates an energy tether linking you to your target.</p>" },
  { name: "Thrown", cost: 1, costType: "flat", category: "feat", fullText: "<p>A close range damage power can be thrown as a ranged attack.</p>" },
  { name: "Transmutation", cost: 1, costType: "flat", category: "feat", fullText: "<p>Adds a new descriptor to your power.</p>" },
  { name: "Triggered", cost: 1, costType: "flat", category: "feat", hasRanks: true, maxRanks: 5, fullText: "<p>You can set the power to activate under a specific condition or trigger.</p>" },
  { name: "Variable Descriptor", cost: 1, costType: "flat", category: "feat", hasRanks: true, maxRanks: 2, tiers: ["Rank 1: Narrow group of descriptors", "Rank 2: Any descriptor"], fullText: "<p>You can change the power's descriptor on the fly as a free action.</p>" },
  
  // Range & Reach Modifiers
  { name: "Extended Range", cost: 1, costType: "flat", category: "feat", hasRanks: true, maxRanks: 10, fullText: "<p>Each rank of Extended Range doubles your power’s range increments (moving the short, medium, and long range distances one step up the range progression). For example, a power with base range 25/50/100 ft. becomes 50/100/250 ft. with 1 rank, 100/250/500 ft. with 2 ranks, and so forth.</p>" },
  { name: "Diminished Range", cost: -1, costType: "flat", category: "flaw", hasRanks: true, maxRanks: 3, fullText: "<p>Each rank of Diminished Range reduces your power’s range increments by one step down the range progression (e.g. standard 25/50/100 ft. becomes 10/25/50 ft. at rank 1, 5/10/25 ft. at rank 2, and 2/5/10 ft. at rank 3). You cannot reduce a power's range below rank 3.</p>" },
  { name: "Reach", cost: 1, costType: "flat", category: "feat", hasRanks: true, maxRanks: 20, fullText: "<p>Each rank of Reach extends your reach with a touch or close range power by 5 feet. For example, 1 rank allows you to touch or strike a target up to 10 feet away without moving, 2 ranks up to 15 feet away, and so on.</p>" },
  { name: "Increased Range", cost: 1, costType: "per_rank", category: "extra", hasRanks: true, maxRanks: 2, tiers: ["Rank 1: Close to Ranged", "Rank 2: Ranged to Perception"], fullText: "<p>Increases the operational range of a power by one step per rank: from Personal to Touch/Close, from Touch/Close to Ranged, or from Ranged to Perception range.</p>" },
  { name: "Reduced Range", cost: -1, costType: "per_rank", category: "flaw", hasRanks: true, maxRanks: 2, tiers: ["Rank 1: Perception to Ranged", "Rank 2: Ranged to Touch"], fullText: "<p>Decreases the operational range of a power by one step per rank: from Perception to Ranged, or from Ranged to Touch/Close range.</p>" },
  { name: "Perception Range", cost: 1, costType: "per_rank", category: "extra", fullText: "<p>The power operates at Perception range: anywhere you can accurately perceive the target with an accurate sense (such as normal sight), with no range penalties and no attack roll required for attack powers.</p>" },
  { name: "Ranged", cost: 1, costType: "per_rank", category: "extra", fullText: "<p>Converts a touch or close range power into a ranged power (with standard range increments of rank × 25 ft. / rank × 50 ft. / rank × 100 ft.).</p>" },
  { name: "Close", cost: -1, costType: "per_rank", category: "flaw", fullText: "<p>Reduces a ranged power to close (touch) range, requiring you to touch or enter melee combat with the target to affect them.</p>" },
  
  // Movement & Teleport Modifiers
  { name: "Extended", cost: 1, costType: "per_rank", category: "extra", fullText: "<p>For sensory effects: each rank increases the sense's range increment by a factor of 10 (-1 Notice penalty per 100 ft. at rank 1, per 1,000 ft. at rank 2, etc.). For movement effects (such as Teleport): allows travel over massive distances using the Extended Range Table as a full-round action.</p>" },
  { name: "Long-Range", cost: -1, costType: "per_rank", category: "flaw", fullText: "<p>You can only use your movement or teleportation effect across your extended range distance as a full-round action. You cannot make short-range tactical teleports or movements as a move action.</p>" },
  { name: "Short-Range", cost: -1, costType: "per_rank", category: "flaw", fullText: "<p>You can only make short-range tactical movements or teleports as a move action; you cannot make extended-range movements or teleports.</p>" },
  { name: "Medium", cost: -1, costType: "per_rank", category: "flaw", fullText: "<p>You require a specific medium to use your power (such as electrical or telephone wires, root structures, waterways, shadows, flames, mirrors, etc.). You can only project from and to locations where your medium exists.</p>" },
  { name: "Easy", cost: 1, costType: "flat", category: "extra", fullText: "<p>You are not disoriented when making full-round extended movements or teleports; you retain your dodge bonus to Defense for the round after arriving at your destination.</p>" },
  { name: "Turnabout", cost: 1, costType: "flat", category: "extra", fullText: "<p>You can teleport or move, take a standard action (such as an attack or skill check), and teleport or move back to your starting point in a single round, so long as the total distance traveled does not exceed your maximum range.</p>" },
  { name: "Change Direction", cost: 1, costType: "flat", category: "extra", fullText: "<p>You can change your facing or orientation after a movement or teleportation action, allowing you to face any direction when arriving at your destination.</p>" },
  { name: "Change Velocity", cost: 1, costType: "flat", category: "extra", fullText: "<p>You arrive “at rest” when you teleport or move. Among other things, this allows you to teleport out of a free fall and suffer no impact or falling damage.</p>" },
  { name: "Castling", cost: 0, costType: "flat", category: "extra", fullText: "<p>You and a willing subject within your teleport range instantly trade places when you activate this power.</p>" },
  
  // Parametric Action & Duration Modifiers
  { name: "Action (Move)", cost: 1, costType: "per_rank", category: "extra", fullText: "<p>Decreases the action required to activate or use the power to a Move action.</p>" },
  { name: "Action (Free)", cost: 2, costType: "per_rank", category: "extra", fullText: "<p>Decreases the action required to activate or use the power to a Free action.</p>" },
  { name: "Action (Reaction)", cost: 3, costType: "per_rank", category: "extra", fullText: "<p>Decreases the action required to activate or use the power to a Reaction in response to a specified trigger.</p>" },
  { name: "Action (Standard)", cost: -1, costType: "per_rank", category: "flaw", fullText: "<p>Increases the action required to activate or use the power to a Standard action.</p>" },
  { name: "Activation (Move)", cost: -1, costType: "flat", category: "flaw", fullText: "<p>Requires a Move action to activate before the power can be used.</p>" },
  { name: "Activation (Standard)", cost: -2, costType: "flat", category: "flaw", fullText: "<p>Requires a Standard action to activate before the power can be used.</p>" },
  { name: "Increased Duration (Concentration)", cost: 1, costType: "per_rank", category: "extra", fullText: "<p>Increases the power’s duration from Instant to Concentration.</p>" },
  { name: "Increased Duration (Sustained)", cost: 1, costType: "per_rank", category: "extra", fullText: "<p>Increases the power’s duration to Sustained, requiring only a free action each round to maintain.</p>" },
  { name: "Increased Duration (Continuous)", cost: 2, costType: "per_rank", category: "extra", fullText: "<p>Increases the power’s duration to Continuous; it remains in effect even if you are stunned or rendered unconscious.</p>" },
  { name: "Decreased Duration (Instant)", cost: -1, costType: "per_rank", category: "flaw", fullText: "<p>Decreases the power’s duration to Instant.</p>" },
  { name: "Decreased Duration (Concentration)", cost: -1, costType: "per_rank", category: "flaw", fullText: "<p>Decreases the power’s duration to Concentration, requiring a standard action each round to maintain.</p>" },
  { name: "Decreased Duration (Sustained)", cost: -1, costType: "per_rank", category: "flaw", fullText: "<p>Decreases the power’s duration from Continuous to Sustained.</p>" }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { POWER_MODIFIERS_LIST };
} else {
  window.POWER_MODIFIERS_LIST = POWER_MODIFIERS_LIST;
}